Revert "[BZ-1072679] manage NoClassDefFoundError as a ClassNotFoundException raising a compilation error when it occurs"
This reverts commit c103ccc2ded90955cf6c208b4dd85455fab2dab5.